version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:rw
    tty: true
    ports:
      - "8000:8000"
    environment:
      - USE_RELOADER=true
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    volumes:
      - .:/frontend:rw
    tty: true
    ports:
      - "3000:3000"
    environment:
      NUXT_PUBLIC_BACKEND_URL: "${BACKEND_URL:-http://0.0.0.0:8000}"
    env_file:
      - .env
